apiVersion: v1
kind: Secret

metadata:
  name: db-connection
type: Opaque

data:
  db_user: cG9zdGdyZXMuaGxrdnN2cXdxcXdldnhnZWpyZ2k=
  db_password: NjU2OEdlbmU0dGlvbkA=
  db_host: YXdzLTAtdXMtd2VzdC0xLnBvb2xlci5zdXBhYmFzZS5jb20=
  db_port: NjU0Mw==
  db_name: cG9zdGdyZXM=
